google.maps.__gjsload__('layers', function(_){var DT=function(a,b,c,d){this.W=a;this.ta=b;this.ka=c;this.j=this.i=null;this.o=this.H=d;this.T=new _.gi(this.$,0,this)},ET=function(a,b,c){_.hh.call(this);this.H=null!=c?(0,_.w)(a,c):a;this.o=b;this.j=(0,_.w)(this.Kl,this);this.i=[]},FT=function(a){a.Pd=_.fi(a.j,a.o);a.H.apply(null,a.i)},IT=function(a,b){var c=GT;this.W=document;this.$=null;this.ta=!1;this.H=!0;this.ua=Math.floor(_.$a()/HT());this.i=null;this.T=new DT(a,c,b,this.Pf());this.ka=!0;this.j=new ET(this.Ka,HT(),this);this.j.Mb();this.o()},
JT=function(a){var b=a.T;a=a.Pf();b.o=a;_.hi(b.T)},HT=function(){return window.__gm_trafficAutoRefreshPeriod||6E5},KT=_.n(),NT=function(a,b,c,d){var e=new _.Qs;e.layerId=b;b=new _.an;b.V[0]=68;var f=_.bn(b);_.$m(f,"set");f.V[1]=d;e.ag=b;var g=new DT(LT(c,a),GT,MT(c,a),e);_.L.hb(a,"map_changed",function(){g.setMap(a.getMap())})},LT=function(a,b){return function(c,d){var e=c.__gm.j;e.set(_.xm(e.get(),d));_.ej(c,a);_.vo(a,"-p",b)}},GT=function(a,b,c){a=a.__gm.j;a.set(_.xm(a.get().Jc(b),c))},MT=function(a,
b){return function(c,d){c=c.__gm.j;c.set(c.get().Jc(d));_.wo(a,"-p",b)}};DT.prototype.setMap=function(a){this.j=a;_.hi(this.T)};DT.prototype.$=function(){this.j==this.i?this.i&&this.ta(this.i,this.H,this.o):(this.i&&this.ka(this.i,this.H),this.j&&this.W(this.j,this.o));this.i=this.j;this.H=this.o};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.A(ET,_.hh);_.t=ET.prototype;_.t.ke=!1;_.t.Ue=0;_.t.Pd=null;_.t.Mb=function(a){this.i=arguments;this.Pd||this.Ue?this.ke=!0:FT(this)};_.t.stop=function(){this.Pd&&(_.z.clearTimeout(this.Pd),this.Pd=null,this.ke=!1,this.i=[])};_.t.wc=function(){ET.Zc.wc.call(this);this.stop()};_.t.Kl=function(){this.Pd=null;this.ke&&!this.Ue&&(this.ke=!1,FT(this))};IT.prototype.setMap=function(a){this.T.setMap(a);this.$=a;this.o();a?this.i||(this.i=_.L.kb(this.W,"visibilitychange",this,this.o)):this.i&&(_.L.removeListener(this.i),this.i=null)};IT.prototype.o=function(){var a=this.H&&!!this.$&&!this.W.hidden;if(a!=this.ka){if(a){var b=this.j;b.Ue--;b.Ue||!b.ke||b.Pd||(b.ke=!1,FT(b))}else this.j.Ue++;this.ka=a}};IT.prototype.Ka=function(){this.ua=Math.floor(_.$a()/HT());JT(this);this.j.Mb()};
IT.prototype.Pf=function(){var a=new _.Qs;a.layerId="traffic";this.ta&&(a.parameters.incidents="1",a.parameters.incidents_text="1");a.parameters.t=this.ua;return a};KT.prototype.j=function(a){var b=new IT(LT("Lt",a),MT("Lt",a));_.L.hb(a,"map_changed",function(){b.setMap(a.getMap())});_.L.hb(a,"showincidents_changed",function(){var c=a.get("showIncidents");b.ta=c;JT(b)});_.L.hb(a,"autorefresh_changed",function(){var c=0!=a.get("autoRefresh");b.H=c;b.o()})};KT.prototype.i=function(a){NT(a,"bike","Lb","NonRoadmap")};KT.prototype.o=function(a){NT(a,"transit","Lr","TransitFocused")};_.Df("layers",new KT);});
